name: Windows VM Setup

on:
  workflow_dispatch:
    inputs:
      code:
        description: "Paste PowerShell Code"
        required: true
        default: "Write-Host 'Hello from GitHub Actions'"

jobs:
  build:
    name: Windows VM Running
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Install Chrome Remote Desktop
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome-remote-desktop/chrome-remote-desktop_current.exe" -OutFile "$env:TEMP\\chrome-remote-desktop.exe"
          Start-Process -FilePath "$env:TEMP\\chrome-remote-desktop.exe" -ArgumentList '/silent', '/install' -Wait

      - name: Execute PowerShell Code
        run: |
          # CONNECTING WITH VM
          $Code = "${{ inputs.code }}"
          Invoke-Expression $Code

      - name: Keep VM Running
        run: |
          # Keep VM alive
          $i = 360
          do {
              Write-Host $i
              Start-Sleep -Seconds 60
              $i--
          } while ($i -gt 0)
