name: TD VM v2

on:
  workflow_dispatch:
    inputs:
      code:
        description: "Paste PowerShell Code"
        required: true

jobs:
  setup_vm:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download Chrome Remote Desktop Installer
        run: |
          # Download from the provided Google Drive link
          $url = "https://drive.google.com/uc?export=download&id=1Iz3sNhl_5OwCzgmnXIQQtAoKSSxPBLJT"
          Invoke-WebRequest -Uri $url -OutFile "chrome_remote_desktop.msi"
        
      - name: Install Chrome Remote Desktop
        run: |
          # Silent install for .msi installer
          Start-Process msiexec.exe -ArgumentList "/i chrome_remote_desktop.msi /quiet /norestart" -NoNewWindow -Wait
          Write-Host "Chrome Remote Desktop installed successfully."

      - name: Run Custom PowerShell Code
        run: |
          # Run custom PowerShell code provided by the user
          $code = "${{ inputs.code }}"
          Invoke-Expression $code
      shell: powershell

      - name: Keep VM Running
        run: |
          # Keeps the workflow running for 6 hours
          for ($i = 360; $i -gt 0; $i--) {
            Write-Host "VM running for $i more minutes"
            Start-Sleep -Seconds 60
          }
