name: Windows VM Setup

on:
  workflow_dispatch:
    inputs:
      code:
        description: "Paste PowerShell Code"
        required: true
        default: "Write-Host 'Hello from GitHub Actions'"

jobs:
  build:
    name: Windows VM Running
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Executing PowerShell Code
        run: |
          # CONNECTING WITH VM
          $Code = ${{ inputs.code }} # Directly get the input code
          $Code = $Code -replace '"', '`"' # Escape any double quotes in the code
          Invoke-Expression $Code

      - name: Keep VM Running
        run: |
          # Go And Connect Now!
          $i = 360
          do {
              Write-Host $i
              Sleep 60
              $i--
          } while ($i -gt 0)
