name: VM Setup with Chrome Remote Desktop and Custom Connection

on:
  workflow_dispatch:
    inputs:
      code:
        description: "Paste PowerShell Code for VM Connection"
        required: true

jobs:
  setup_vm:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download Chrome Remote Desktop Installer
        shell: powershell
        run: |
          # Download from the provided Google Drive link
          $url = "https://drive.google.com/uc?export=download&id=1Iz3sNhl_5OwCzgmnXIQQtAoKSSxPBLJT"
          Invoke-WebRequest -Uri $url -OutFile "chrome_remote_desktop.msi"
        
      - name: Install Chrome Remote Desktop
        shell: powershell
        run: |
          # Install the .msi file silently
          Start-Process msiexec.exe -ArgumentList "/i chrome_remote_desktop.msi /quiet /norestart" -NoNewWindow -Wait
          Write-Host "Chrome Remote Desktop installed successfully."

      - name: Run Custom Connection Code
        shell: powershell
        run: |
          # Run the custom PowerShell code provided by the user for VM connection
          $code = "${{ inputs.code }}"
          Invoke-Expression $code
          
      - name: Keep VM Running
        shell: powershell
        run: |
          # Keeps the workflow running for remote access
          $i = 360
          do {
              Write-Host "VM running for $i more minutes"
              Start-Sleep -Seconds 60
              $i--
          } while ($i -gt 0)
